import type { Prisma } from "@prisma/client";
import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { prisma } from "../../plugins/prisma.js";
import { requireAdmin } from "../auth/guards.js";
import { storage } from "../storage/storage.js";
import { productForApi, productInclude, recordPriceChange, uniqueSlug } from "./service.js";

const idSchema = z.object({ id: z.string().min(1) });
const slugSchema = z.object({ slug: z.string().min(1) });
const dateSchema = z.string().datetime().nullable().optional();
const productBase = z.object({ name: z.string().trim().min(2).max(160), description: z.string().trim().min(1).max(10000), costPrice: z.coerce.number().nonnegative().finite(), salePrice: z.coerce.number().nonnegative().finite(), active: z.boolean().optional(), featured: z.boolean().optional(), displayOrder: z.coerce.number().int().min(0).optional(), salesStartAt: dateSchema, salesEndAt: dateSchema });
const productBody = productBase.superRefine((data, ctx) => { const start = data.salesStartAt ? new Date(data.salesStartAt) : null; const end = data.salesEndAt ? new Date(data.salesEndAt) : null; if (start && end && end <= start) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["salesEndAt"], message: "O fim das vendas deve ser posterior ao inicio." }); });
const variantBody = z.object({ name: z.string().trim().min(1).max(100), active: z.boolean().optional(), displayOrder: z.coerce.number().int().min(0).optional() });
const imageBody = z.object({ type: z.enum(["PRODUCT", "SIZE_GUIDE"]), altText: z.string().trim().min(1).max(200), displayOrder: z.coerce.number().int().min(0).optional(), fileName: z.string().min(1).max(255), mimeType: z.string(), contentBase64: z.string().min(1) });
const imageUpdateBody = z.object({ altText: z.string().trim().min(1).max(200).optional(), displayOrder: z.coerce.number().int().min(0).optional() });
const publicWindow = (): Prisma.ProductWhereInput => ({ active: true, AND: [{ OR: [{ salesStartAt: { lte: new Date() } }, { salesStartAt: null }] }, { OR: [{ salesEndAt: { gte: new Date() } }, { salesEndAt: null }] }] });
function missing(reply: any, message = "Produto nao encontrado.") { return reply.status(404).send({ error: { code: "NOT_FOUND", message } }); }

export const productRoutes: FastifyPluginAsync = async (app) => {
  app.get("/uploads/:key", async (request, reply) => { const key = z.object({ key: z.string() }).parse(request.params).key; const content = await storage.read(key); if (!content) return reply.status(404).send(); return reply.type(key.endsWith(".png") ? "image/png" : key.endsWith(".webp") ? "image/webp" : "image/jpeg").send(content); });
  app.get("/products", async () => { const products = await prisma.product.findMany({ where: publicWindow(), include: productInclude, orderBy: [{ featured: "desc" }, { displayOrder: "asc" }, { createdAt: "desc" }] }); return { products: products.map((product) => productForApi(product)) }; });
  app.get("/products/:slug", async (request, reply) => { const product = await prisma.product.findFirst({ where: { slug: slugSchema.parse(request.params).slug, ...publicWindow() }, include: { variants: { where: { active: true, deletedAt: null }, orderBy: { displayOrder: "asc" } }, images: { where: { deletedAt: null }, orderBy: { displayOrder: "asc" } } } }); return product ? { product: productForApi(product) } : missing(reply); });

  app.get("/admin/products", { preHandler: requireAdmin }, async () => { const products = await prisma.product.findMany({ include: productInclude, orderBy: [{ displayOrder: "asc" }, { createdAt: "desc" }] }); return { products: products.map((product) => productForApi(product, true)) }; });
  app.get("/admin/products/:id", { preHandler: requireAdmin }, async (request, reply) => { const product = await prisma.product.findFirst({ where: idSchema.parse(request.params), include: productInclude }); return product ? { product: productForApi(product) } : missing(reply); });
  app.post("/admin/products", { preHandler: requireAdmin }, async (request) => { const data = productBody.parse(request.body); const product = await prisma.product.create({ data: { ...data, salesStartAt: data.salesStartAt ? new Date(data.salesStartAt) : null, salesEndAt: data.salesEndAt ? new Date(data.salesEndAt) : null, slug: await uniqueSlug(data.name), active: data.active ?? false, featured: data.featured ?? false, displayOrder: data.displayOrder ?? 0 }, include: productInclude }); return { product: productForApi(product) }; });
  app.patch("/admin/products/:id", { preHandler: requireAdmin }, async (request, reply) => { const { id } = idSchema.parse(request.params); const data = productBase.partial().parse(request.body); const current = await prisma.product.findFirst({ where: { id } }); if (!current) return missing(reply); const product = await prisma.product.update({ where: { id }, data: { ...Object.fromEntries(Object.entries(data).filter(([, value]) => value !== undefined)), ...(data.salesStartAt !== undefined ? { salesStartAt: data.salesStartAt ? new Date(data.salesStartAt) : null } : {}), ...(data.salesEndAt !== undefined ? { salesEndAt: data.salesEndAt ? new Date(data.salesEndAt) : null } : {}), ...(data.name ? { slug: await uniqueSlug(data.name, id) } : {}) }, include: productInclude }); await recordPriceChange(request.currentUser!.id, id, current.salePrice, product.salePrice); return { product: productForApi(product) }; });
  app.delete("/admin/products/:id", { preHandler: requireAdmin }, async (request, reply) => { const { id } = idSchema.parse(request.params); if (!await prisma.product.findFirst({ where: { id } })) return missing(reply); await prisma.product.update({ where: { id }, data: { deletedAt: new Date(), active: false } }); return reply.status(204).send(); });

  app.post("/admin/products/:id/variants", { preHandler: requireAdmin }, async (request, reply) => { const productId = idSchema.parse(request.params).id; if (!await prisma.product.findFirst({ where: { id: productId } })) return missing(reply); const data = variantBody.parse(request.body); return { variant: await prisma.productVariant.create({ data: { productId, name: data.name, active: data.active ?? true, displayOrder: data.displayOrder ?? 0 } }) }; });
  app.patch("/admin/products/:id/variants/:variantId", { preHandler: requireAdmin }, async (request, reply) => { const params = z.object({ id: z.string(), variantId: z.string() }).parse(request.params); const found = await prisma.productVariant.findFirst({ where: { id: params.variantId, productId: params.id } }); if (!found) return missing(reply, "Variante nao encontrada."); return { variant: await prisma.productVariant.update({ where: { id: found.id }, data: Object.fromEntries(Object.entries(variantBody.partial().parse(request.body)).filter(([, value]) => value !== undefined)) }) }; });
  app.delete("/admin/products/:id/variants/:variantId", { preHandler: requireAdmin }, async (request, reply) => { const params = z.object({ id: z.string(), variantId: z.string() }).parse(request.params); const found = await prisma.productVariant.findFirst({ where: { id: params.variantId, productId: params.id } }); if (!found) return missing(reply, "Variante nao encontrada."); await prisma.productVariant.update({ where: { id: found.id }, data: { active: false, deletedAt: new Date() } }); return reply.status(204).send(); });

  app.post("/admin/products/:id/images", { preHandler: requireAdmin }, async (request, reply) => { const productId = idSchema.parse(request.params).id; if (!await prisma.product.findFirst({ where: { id: productId } })) return missing(reply); const data = imageBody.parse(request.body); const stored = await storage.upload(data); return { image: await prisma.productImage.create({ data: { productId, type: data.type, altText: data.altText, displayOrder: data.displayOrder ?? 0, url: stored.url } }) }; });
  app.patch("/admin/products/:id/images/:imageId", { preHandler: requireAdmin }, async (request, reply) => { const params = z.object({ id: z.string(), imageId: z.string() }).parse(request.params); const found = await prisma.productImage.findFirst({ where: { id: params.imageId, productId: params.id } }); if (!found) return missing(reply, "Imagem nao encontrada."); return { image: await prisma.productImage.update({ where: { id: found.id }, data: Object.fromEntries(Object.entries(imageUpdateBody.parse(request.body)).filter(([, value]) => value !== undefined)) }) }; });
  app.delete("/admin/products/:id/images/:imageId", { preHandler: requireAdmin }, async (request, reply) => { const params = z.object({ id: z.string(), imageId: z.string() }).parse(request.params); const found = await prisma.productImage.findFirst({ where: { id: params.imageId, productId: params.id } }); if (!found) return missing(reply, "Imagem nao encontrada."); await prisma.productImage.update({ where: { id: found.id }, data: { deletedAt: new Date() } }); return reply.status(204).send(); });
};